version: "3"
  
services:
  nginx:
    image: nginx:1.17.10
    container_name: zinzaraNginx
    ports:
      - "80:80"
    volumes:
      - ./zinzaraServer:/zinzaraServer
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    container_name: zinzaraWeb
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn zinzaraServer.wsgi:application -b 0:80"
    volumes:
      - ./zinzaraServer:/zinzaraServer
    depends_on:
      - db

  db:
    image: mariadb:10.4
    container_name: zinzaraDB
    environment:
      - TZ="Asia/Seoul"
      - MYSQL_ROOT_PASSWORD:zinzara123
      - MYSQL_DATABASE:zinzara
      - MYSQL_USER:root
      - MYSQL_PASSWORD:zinzara123