# Generated by Django 3.1.3 on 2022-03-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=30, primary_key=True, serialize=False)),
                ('pw', models.CharField(db_column='pw', max_length=15)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=13)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created')),
            ],
            options={
                'db_table': 'members',
                'ordering': ['created'],
            },
        ),
    ]
