# Generated by Django 3.1.3 on 2022-03-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gestures',
            table='gestures',
        ),
    ]
