# Generated by Django 3.1.3 on 2022-02-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestures',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
