# Generated by Django 3.1.3 on 2022-01-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physical_rehabilitation',
            fields=[
                ('physical_score', models.IntegerField(db_column='physical_score')),
                ('rehabilitation_time', models.DateTimeField(auto_now_add=True, db_column='rehabilitation_time')),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='members.members', unique=True)),
            ],
            options={
                'db_table': 'physical_rehabilitation',
            },
        ),
        migrations.CreateModel(
            name='Language_rehabilitation',
            fields=[
                ('language_score', models.IntegerField(db_column='language_score')),
                ('rehabilitation_time', models.DateTimeField(auto_now_add=True, db_column='rehabilitation_time')),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='members.members', unique=True)),
            ],
            options={
                'db_table': 'language_rehabilitation',
            },
        ),
    ]
